# Example configuration for tc_router

# BPF object
obj=./tc_router_kern.o

# mode=attach or detach
mode=attach
#mode=detach

# watch for neighbor updates (ARP/Netlink)
watch=1
# auto_detach on exit (default: same as watch)
auto_detach=1
# auto ping next-hop when neighbor missing
ping_on_miss=1

# tc filter handle/prio base
handle=1
prio=1

# Devices to attach for forwarding traffic (ingress)
attach_ingress_devs=enp0s3

# Devices to attach for local traffic (egress)
# Example: enp0s3 (default route device)
attach_egress_devs=enp0s3

# Routes: src_ip,next_hop_ip,egress_dev
route=10.10.1.1,172.16.1.254,veth0
route=10.10.1.2,172.16.2.254,veth1
